##
## Makefile for  in /home/chatea_s/project/unix/lemipc
## 
## Made by Sylvain Chateau
## Login   <chatea_s@epitech.net>
## 
## Started on  Sat Mar 29 20:22:50 2014 Sylvain Chateau
## Last update Sat Mar 29 20:24:32 2014 Sylvain Chateau
##

all:
	$(MAKE) -C lemipc
	$(MAKE) -C display

clean:
	$(MAKE) -C lemipc clean
	$(MAKE) -C display clean

fclean:
	$(MAKE) -C lemipc fclean
	$(MAKE) -C display fclean

re:
	$(MAKE) -C lemipc re
	$(MAKE) -C display re
