##
## Makefile for  in /home/chatea_s/zappy
## 
## Made by 
## Login   <chatea_s@epitech.net>
## 
## Started on  Thu Jun 19 21:09:41 2014 
## Last update Sun Jul 13 22:38:48 2014 Arthur Coudert
##

all:
	@make -s -C server all
	@make -s -C graphic all

clean:
	@make -s -C server clean
	@make -s -C graphic clean

fclean:
	@make -s -C server fclean
	@make -s -C graphic fclean

dclean:
	@make -s -C server dclean
	@make -s -C graphic dclean

re:	fclean all

.PHONY:	all clean fclean re
