##
## Makefile for  in /home/chatea_s/project/rush/rush/rush
## 
## Made by Sylvain Chateau
## Login   <chatea_s@epitech.net>
## 
## Started on  Sat Mar  8 02:41:05 2014 Sylvain Chateau
## Last update Sat Apr  5 12:50:09 2014 Sylvain Chateau
##

all:
	$(MAKE) -C core
	$(MAKE) -C lib_Ncurses
	$(MAKE) -C lib_OpenGL
	$(MAKE) -C lib_SFML

clean:
	$(MAKE) -C core clean
	$(MAKE) -C lib_Ncurses clean
	$(MAKE) -C lib_OpenGL clean
	$(MAKE) -C lib_SFML clean

fclean:
	$(MAKE) -C core fclean
	$(MAKE) -C lib_Ncurses fclean
	$(MAKE) -C lib_OpenGL fclean
	$(MAKE) -C lib_SFML fclean


re:
	$(MAKE) -C core re
	$(MAKE) -C lib_Ncurses re
	$(MAKE) -C lib_OpenGL re
	$(MAKE) -C lib_SFML re

